BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Article] (
    [id] INT NOT NULL IDENTITY(1,1),
    [Cd_Article] NVARCHAR(1000) NOT NULL,
    [Cd_UM] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Article_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Article_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Article_Cd_Article_key] UNIQUE NONCLUSTERED ([Cd_Article]),
    CONSTRAINT [Article_Cd_UM_key] UNIQUE NONCLUSTERED ([Cd_UM])
);

-- CreateTable
CREATE TABLE [dbo].[UM] (
    [id] INT NOT NULL IDENTITY(1,1),
    [Cd_UM] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [UM_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [UM_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [UM_Cd_UM_key] UNIQUE NONCLUSTERED ([Cd_UM])
);

-- AddForeignKey
ALTER TABLE [dbo].[Article] ADD CONSTRAINT [FK_Article_UM] FOREIGN KEY ([Cd_UM]) REFERENCES [dbo].[UM]([Cd_UM]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
